num1 = int(input("enter first no:"))
num2 = int(input("enter second no:"))
addition = (num1+num2)
print("addition",addition)
difference = (num1-num2)
print("diference",difference)
multiplication=(num1*num2)
print("multiplication",multiplication)
division = (num1/num2)
print("division",division)
