n1 = int(input("enter the width:"))
n2 = int(input("enter the length:"))
rectangle = (n1*n2)
print("area of the rectangle",rectangle)
n11 = int(input("enter the base:"))
n22 = int(input("enter the length:"))
tri = float(n11*n22*.5)
print("area of the triangle:",tri)
n111 = int(input("enter the radious"))
cir=float(n11*n11*3.14)
print("area of cirle",cir)
